# Project: 13
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = 
OBJ  = 13.o $(RES)
LINKOBJ  = 13.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" ../../../../Dev-Cpp/lib/glut.lib ../../../../Dev-Cpp/lib/glut32.lib ../../../../Dev-Cpp/lib/libopengl32.a  -lgmon -pg  -g3 
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/include/GL" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/include/GL" 
BIN  = 13.a
CXXFLAGS = $(CXXINCS)   -pg -g3
CFLAGS = $(INCS)   -pg -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before 13.a all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(LINKOBJ)
	ar r $(BIN) $(LINKOBJ)
	ranlib $(BIN)

13.o: 13.cpp
	$(CPP) -c 13.cpp -o 13.o $(CXXFLAGS)
