# Project: CodeHunters
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = 
OBJ  = DayD_01.o DayD_02.o DayD_03.o Безымянный1.o $(RES)
LINKOBJ  = DayD_01.o DayD_02.o DayD_03.o Безымянный1.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  ../../../../../Dev-Cpp/lib/libd3d9.a  -g3 
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/include/GL" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/include/GL" 
BIN  = CodeHunters.exe
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS)   -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before CodeHunters.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "CodeHunters.exe" $(LIBS)

DayD_01.o: DayD_01.cpp
	$(CPP) -c DayD_01.cpp -o DayD_01.o $(CXXFLAGS)

DayD_02.o: DayD_02.cpp
	$(CPP) -c DayD_02.cpp -o DayD_02.o $(CXXFLAGS)

DayD_03.o: DayD_03.cpp
	$(CPP) -c DayD_03.cpp -o DayD_03.o $(CXXFLAGS)

Безымянный1.o: Безымянный1.cpp
	$(CPP) -c Безымянный1.cpp -o Безымянный1.o $(CXXFLAGS)
