/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef GAME_PRERELIS_1_PRIVATE_H
#define GAME_PRERELIS_1_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"0.1.3.1"
#define VER_MAJOR	0
#define VER_MINOR	1
#define VER_RELEASE	3
#define VER_BUILD	1
#define COMPANY_NAME	""
#define FILE_VERSION	"PreRelise 1"
#define FILE_DESCRIPTION	"Dahaka_inc"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"CheckNumber"
#define PRODUCT_VERSION	"3"

#endif /*GAME_PRERELIS_1_PRIVATE_H*/
