# Project: Game_PreRelis_1
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe -D__DEBUG__
CC   = gcc.exe -D__DEBUG__
WINDRES = windres.exe
RES  = Game_PreRelis_1_private.res
OBJ  = Bt-6.o $(RES)
LINKOBJ  = Bt-6.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  -g3 
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include" 
BIN  = Game_PreRelis_1.exe
CXXFLAGS = $(CXXINCS)   -g3
CFLAGS = $(INCS)   -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before Game_PreRelis_1.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "Game_PreRelis_1.exe" $(LIBS)

Bt-6.o: Bt-6.cpp
	$(CPP) -c Bt-6.cpp -o Bt-6.o $(CXXFLAGS)

Game_PreRelis_1_private.res: Game_PreRelis_1_private.rc 
	$(WINDRES) -i Game_PreRelis_1_private.rc --input-format=rc -o Game_PreRelis_1_private.res -O coff 
